server:
  port: 9003

spring:
  application:
    name: USERS

  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/users
    password: 'postgres'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka